home/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views

app_name = 'todo'
urlpatterns = [
    path('', views.home, name='home'),
    path('tasks/', views.tasks, name='tasks'),
    path('delete/<int:id>', views.delete, name='delete'),
    path('search',views.search,name='search'),
]


todolist/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls'))
]

home/models.py
from django.db import models
# Create your models here.


class Task(models.Model):
    tasktitle = models.CharField(max_length=30)
    taskdesc = models.TextField()
    time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.tasktitle

home/views.py
from django.shortcuts import render,HttpResponse,get_object_or_404,redirect
from home.models import Task
# Create your views here.


def home(request):
    context = {'success': False}
    if request.method == "POST":
        title = request.POST['title'] #handle form
        desc = request.POST['desc']
        print(title,desc)
        ins = Task(tasktitle=title, taskdesc=desc)
        ins.save()
        context = {'success': True}

    return render(request,'index.html', context)


def tasks(request):
    alltasks = Task.objects.all()
    context = {'tasks': alltasks}
    return render(request,'tasks.html',context)


def delete(request,id):
    delitem = Task.objects.get(pk=id)
    delitem.delete()
    return redirect('/tasks')


"""def edit(request,id):
    updateitem = Task.objects.get(pk=id)
    context = {'title' : updateitem.title,
               'desc': updateitem.desc,
               'id':updateitem.id}
    return render(request,'edit.html',context)
    
def update(request,id):
    obj = Task(id=id)
    obj.title = request.GET['title']  # handle form
    obj.desc = request.GET['desc']
    obj.save()
    context = {"alltodos" : Task.objects.all()}
    return render(request, 'index.html', context)"""


def search(request):
    if request.method=='GET':
        q = request.GET['q'].upper()
        task = Task.objects.all().filter(tasktitle__icontains=q)
        return render(request,'tasks.html',{'tasks':task})

templates/edit.html
{% extends 'task.html' %}
{% block title %}EDIT Todo (% endblock %}
{% block content %}
      <div class="container my-3">
      <form action="/update/{{id}}">
      {% csrf_token %}
        <div class="form-group">
            <label for="title" > Task Title</label>
           <input type="title" class="form-control" id="title" name="title", value={{tasktitle}}>
        </div>
        <div class="form-group">
            <label for="desc"> Task Description</label>
            <textarea name="desc" type="desc" class="form-control" id="desc" col="20", rows="10">{{taskdesc}}</textarea>
        </div>
          <button type="submit" class="btn btn-primary" style="background-color:green;">Update</button>
      </form>
      </div>
{% endblock %}

templates/index.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <title>Home - TODOs LIST!</title>
    <style>
      body {background-color: mistyrose;}
      h2   {color: olive;}
      h3 {color: blue;}
    </style>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">TODOs-LIST</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="tasks/">Tasks</a>
          </li>
        </ul>
      </div>
      </div>
    </nav>
     {% if success %}
      <div class="alert alert-success alert-dismissible fade show" role="alert">
         <strong>Success:</strong> Task has been added to your list.
         <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {% endif %}
      <div class="container my-3">
        <h2 class="text-center py-1">
          <B class="text-center"> WELCOME TO TODOs-LIST </B>
        </h2>
        <H3 class="text-center"> ADD A TASK :)</H3>
      <form action="/" method="post">
      {% csrf_token %}
        <div class="form-group">
            <label for="title" > Task Title</label>
           <input type="title" class="form-control" id="title" name="title">
        </div>
        <div class="form-group">
            <label for="desc"> Task Description</label>
            <input name="desc" type="desc" class="form-control" id="desc" col="20", rows="40"></input>
        </div>
          <button type="submit" class="btn btn-primary" style="background-color:green;">Submit</button>
      </form>
      </div>
    <footer>
       <p class="text-center bg-dark text-light fixed-bottom my-0 py-2">
         Copyright &copy; 2021 || All rights are reserved || Sneha Dhumal &hearts;
       </p>
    </footer>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
    -->
  </body>
</html>

templates/tasks.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="/DataTables/datatables.css">

    <script type="text/javascript" charset="utf8" src="/DataTables/datatables.js"></script>

    <title>TASK-TODOs-LIST!</title>
    <style>
      body {background-color: mistyrose;}
      h2   {color: rgb(102, 0, 102);}
    </style>
  </head>
  <body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">TODOs-LIST</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link " aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="tasks/">Tasks</a>
        </li>
      </ul>
      <form class="d-flex" action="{% url 'todo:search' %}" method='get'>
         <input name='q' type="text" class="form-control" placeholder="Search..">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
  </nav>

  <div class="container my-3">
    <h1 class="text-center">
      <h2 class="text-center"><b><u>YOUR TODOs-LIST</u></b></h2>
    </h1>
   <table class="table">
  <thead>
   <tr class="text-center">
      <th scope="col" class="text-center">*</th>
      <th scope="col" class="text-center"><h5><b>Task Title</h5></b></th>
      <th scope="col" class="text-center"><h5><b>Task Description</h5></b></th>
      <th scope="col" class="text-center">Delete Task</th>
    </tr>
  </thead>
  <tbody>
  {% comment %} Run a for loop and iterate through all the task {% endcomment %}
  {% for task in tasks %}
    <tr class="text-center">
      <th scope="row">{{forloop.counter}}</th>
      <td>{{task.tasktitle}}</td>
      <td>{{task.taskdesc}}</td>
      <td><a href="{% url 'todo:delete' task.id %}"><button>Delete</button></a></td>
    </tr>
  {% endfor %}
  </tbody>
</table>
  </div>
   <footer>
    <p class="text-center bg-dark text-light fixed-bottom my-0 py-2">
      Copyright &copy; 2021 || All rights are reserved || Sneha Dhumal &hearts;
    </p>
  </footer>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
    -->
  </body>
</html>